### ISSUE TITLE
Mapbox Compatibility (MGLMapView)

### ISSUE THREAD

**Issue by superandrew** [mhergon/RealmGeoQueries#1]
Hi, I am using RealmGeoQueries with Mapbox, so I added this extension to RealmGeoQueries.swift

```swift
public extension MGLMapView {
    
   
    var geoBox: GeoBox {
        
        let maxLat = self.visibleCoordinateBounds.ne.latitude
        let minLat = self.visibleCoordinateBounds.sw.latitude
        let maxLng = self.visibleCoordinateBounds.ne.longitude
        let minLng = self.visibleCoordinateBounds.sw.longitude
        
        return GeoBox(
            topLeft: CLLocationCoordinate2D(latitude: maxLat, longitude: minLng),
            bottomRight: CLLocationCoordinate2D(latitude: minLat, longitude: maxLng)
        )
        
    }
    
}
```

I would have filed a pull request, however I don't know how to make the Import MapBox optional for those who don't want to use it.

**Comment by mhergon** [comment]
Maybe the best way is creating another library extension and publishing on Cocoapods or similar.
I want make the RealmGeoQueries completely independent from another libraries.
