### ISSUE TITLE
MKCoordinateRegionMakeWithDistance was obsoleted in Swift 3

### ISSUE THREAD

**Issue by dvera128** [mhergon/RealmGeoQueries#11]
Hi!
I'm trying to use your library with Xcode 10.1 and Swift 4.2 but I having the following error:

`'MKCoordinateRegionMakeWithDistance' has been replaced by 'MKCoordinateRegion.init(center:latitudinalMeters:longitudinalMeters:)'`

Please add support for Swift 4.2

Thanks

**Comment by mhergon** [comment]
Fixed
Carthage is available right now.
Pod will be available in few minutes.
