### ISSUE TITLE
Collection Format Different

### ISSUE THREAD

**Issue by vishaldroisys** [mhergon/RealmGeoQueries#16]
Hello,

I have collection which have following format:

class Account: Object {
    @objc dynamic var GeoLocation: A360_M_Account_V2_GeoLocation?
}

class A360_M_Account_V2_GeoLocation: EmbeddedObject {
    let coordinates = RealmSwift.List<Double>()
    @objc dynamic var type: String? = nil
}

How to sort by distance with these kind of format??

Thanks in advance.

**Comment by mhergon** [comment]
Why do you store coordinates as an array?
The coordinates should go separately as properties

**Comment by vishaldroisys** [comment]
We are using MOngoDB Realm serverless platform and in MongoDB, there is format like mentioned above.

**Comment by mhergon** [comment]
I don't know how it works. This library works on "classic" Realm.
You must set two properties for latitude & longitude.

**Comment by vishaldroisys** [comment]
Any suggestion to Optimization??

Thanks

**Comment by mhergon** [comment]
Is there no optimization, you must use separated properties
Sorry
