### ISSUE TITLE
Why it is not working with MongoDB Realm

### ISSUE THREAD

**Issue by vishaldroisys** [mhergon/RealmGeoQueries#17]
Hello,

As you know that realm is acquired by Mongo. so right now fetching records as per the distance is not working as of now.

Thanks in advanced.

**Comment by mhergon** [comment]
Hi,

Can you share version of Realm? Any example code?

Thanks

**Comment by vishaldroisys** [comment]
i am using MongoDB realm Version 10.0.0-beta.2.

**Comment by vishaldroisys** [comment]
https://docs.mongodb.com/realm/ios/

**Comment by mhergon** [comment]
Sorry, is not planned add support for MongoDB Realm in a short time.
I will work on this as soon as possible

**Comment by Wemps** [comment]
Hey team! Anyone happen to know what the latest version of Realm that this library works with?

**Comment by Wemps** [comment]
I didn't have any issues with 10.0.0.

**Comment by vishaldroisys** [comment]
@Wemps This is worked for both realm & mongoDB realm.

Mongo has acquired Realm so Mongo has launched new SDK i.e. MongoDB realm. MongoDB realm is serverless platform so mongoDB realm has not ROS. In realm there is ROS.

for more reference. please look into below link:
https://docs.mongodb.com/realm/ios/realms/

**Comment by mhergon** [comment]
Hi @Wemps @vishaldroisys 

Can you confirma that library works on original Realm and MongoDB versions?

Thanks!
