### ISSUE TITLE
use MapBox SDK as replacement...

### ISSUE THREAD

**Issue by sirvon** [mhergon/RealmGeoQueries#2]
Thanks for this lib.

Is there any plug and play way to substitute MapBox Map for MapKit?

**Comment by mhergon** [comment]
MapKit is used only for search inside a `MKCoordinateRegion`. What do you need?

**Comment by sirvon** [comment]
ahhh I see this is for pure logic...it's not integrated with a map sdk.
Which is great!

How sufficient is that code for production...what are the shortcomings?

**Comment by mhergon** [comment]
I used my library in production environment and works fine.
I have not found any shortcomings until now.
