### ISSUE TITLE
error: could not build Objective-C module 'GeoQueries'

### ISSUE THREAD

**Issue by grantspilsbury** [mhergon/RealmGeoQueries#3]
Hi,

When I try print out one of my objects to the debugger console area I get the following error:
```
(lldb) po events
error: in auto-import:
failed to get module 'Pulse' from AST context:
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/GeoQueries-Swift.h"
        ^

error: /Users/gs/Library/Developer/Xcode/DerivedData/Pulse-cvkoiqauohlejddryiycdlpbhhev/Build/Products/Debug-iphonesimulator/RealmGeoQueries/GeoQueries.framework/Headers/GeoQueries-Swift.h:141:12: error: cannot find interface declaration for 'RealmSwiftObject'
@interface RealmSwiftObject (SWIFT_EXTENSION(GeoQueries))
           ^

error: could not build Objective-C module 'GeoQueries'
```

Any idea what could be the issue?

**Comment by mhergon** [comment]
Try `po print(events)` or `po events.description` after clean project an `Derived Data`

**Comment by grantspilsbury** [comment]
I will try that. Thanks! 

One more question: Is there anyway to get Realm Results for nearby locations? The findNearby() returns an array and not Results.

**Comment by mhergon** [comment]
Sorry, for the moment is not possible.
`findNearby()` needs a `radius` that is a computed property. Computed property can't be used with `NSPredicate` and the query is made manually:

```
let radius = distance.filter { (obj: Object) -> Bool in
       return obj.objDist <= radius            
}
```

**Comment by grantspilsbury** [comment]
Ok thanks Marc. And thanks for RealmGeoQueries. It's been a big help. 

On May 14, 2017, at 9:29 PM, Marc Hervera <notifications@github.com> wrote:

Sorry, for the moment is not possible.
findNearby() needs a radius that is a computed property. Computed property can't be used with 'NSPredicate' and the query is made manually:

let radius = distance.filter { (obj: Object) -> Bool in
       return obj.objDist <= radius            
}
