### ISSUE TITLE
Use of undeclared type 'T' Xcode 9

### ISSUE THREAD

**Issue by darioken** [mhergon/RealmGeoQueries#6]
Hello.

I have this issue since i update to Xcode 9.

<img width="236" alt="captura de pantalla 2017-10-03 a la s 10 22 43" src="https://user-images.githubusercontent.com/3793353/31127303-e73b00ea-a824-11e7-88dd-7ebebdfee4c9.png">

Thx

**Comment by mhergon** [comment]
CocoaPods or Carthage?
With Carthage compiles fine...

**Comment by darioken** [comment]
CocoaPods

**Comment by darioken** [comment]
I update Realm to 3.0 version.

func filterGeoRegion(region: MKCoordinateRegion, latitudeKey: String = "lat", longitudeKey: String = "lng") -> Results<T> {
        
        let box = region.geoBox
        
        let topLeftPredicate = NSPredicate(format: "%K <= %f AND %K >= %f", latitudeKey, box.topLeft.latitude, longitudeKey, box.topLeft.longitude)
        let bottomRightPredicate = NSPredicate(format: "%K >= %f AND %K <= %f", latitudeKey, box.bottomRight.latitude, longitudeKey, box.bottomRight.longitude)
        let compoundPredicate = NSCompoundPredicate(andPredicateWithSubpredicates: [topLeftPredicate, bottomRightPredicate])
        
        return self.filter(compoundPredicate)
        
    }



This is one of the functions with that problem

**Comment by mhergon** [comment]
Solved in https://github.com/mhergon/RealmGeoQueries/releases/tag/v1.3-pre-release
